/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jukeboxapplication;


import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;

/**
 *
 * @author berkb
 */
public class appMainScreen extends javax.swing.JFrame {
    user userapp ; 
    ArrayList<music> allmusics = new ArrayList<music>();
    ArrayList<music> searchmusics = new ArrayList<music>();
    ArrayList<music> playlist = new ArrayList<music>();
    loginsql sql ; 
    
    File musicpath = null ; 
    AudioInputStream audioInput = null ; 
    Clip clip = null ; 
    long clipTimePosition = 0 ; 

    
    public void showallmusic(loginsql sql , ArrayList<music> arr){
        arr.removeAll(arr);
        sql.musicinfo(arr);
        DefaultTableModel model =  (DefaultTableModel) musictable.getModel();
        for(music music : arr ){
            Object[] addiable = {music.getMusicName() , music.getArtistName() , music.getMusicType()};
            model.addRow(addiable);
            
        }
    }
 
    public appMainScreen(user user , loginsql sql ) {
        this.sql = sql ;
        initComponents();
        userapp = user ;
        usernnamenamearea.setText(userapp.getUserName());
        showallmusic(sql,allmusics);
 
    }

    public void deletetable(){
        DefaultTableModel model = (DefaultTableModel) musictable.getModel();
        int rowcount = musictable.getRowCount() -1 ;
        while (rowcount != -1) {
            model.removeRow(rowcount);
            rowcount-- ; 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        usernnamenamearea = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        logoutbutton = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        exitbutton = new javax.swing.JLabel();
        pausesongbutton = new javax.swing.JLabel();
        playsongbutton = new javax.swing.JLabel();
        playingsongname = new javax.swing.JLabel();
        playingsonsingername = new javax.swing.JLabel();
        tablename = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        musictable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        deletefromdatabase = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        addnewsongbutton = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        addsongtoplaylistbutton = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        showplaylistbutton = new javax.swing.JLabel();
        removesongfromplaylist = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        searchsongname = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        searchsingername = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        combotypebox = new javax.swing.JComboBox<>();
        serachlabelbutton = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        allsongshowbutton = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        playsongname = new javax.swing.JLabel();
        selectedsongname = new javax.swing.JLabel();
        selectedsongsingername = new javax.swing.JLabel();
        selectedsongtype = new javax.swing.JLabel();
        firsttimeplaybutton = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 204, 102));
        jPanel2.setForeground(new java.awt.Color(255, 204, 102));

        jLabel45.setIcon(new javax.swing.ImageIcon("C:\\Users\\berkb\\OneDrive\\Masaüstü\\Png and Icons\\Vector Icons\\02- Regular\\06-PNG\\48w\\rat.png")); // NOI18N
        jLabel45.setText("jLabel3");

        jLabel46.setFont(new java.awt.Font("Ink Free", 0, 24)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(0, 153, 153));
        jLabel46.setText(" RAT MUSIC");
        jLabel46.setToolTipText("");

        usernnamenamearea.setFont(new java.awt.Font("Ink Free", 0, 24)); // NOI18N
        usernnamenamearea.setText("berk");

        jLabel4.setFont(new java.awt.Font("Ink Free", 0, 24)); // NOI18N
        jLabel4.setText("WELCOME ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel46)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernnamenamearea, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(usernnamenamearea)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));

        logoutbutton.setIcon(new javax.swing.ImageIcon("C:\\Users\\berkb\\OneDrive\\Masaüstü\\Png and Icons\\Streamline_All_Icons_PNG\\PNG Icons\\02- Regular\\01-Interface Essential\\04-Login-Logout\\48w\\logout-2.png")); // NOI18N
        logoutbutton.setText("jLabel1");
        logoutbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutbuttonMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ink Free", 0, 14)); // NOI18N
        jLabel1.setText("LogOut");

        jLabel2.setFont(new java.awt.Font("Ink Free", 0, 14)); // NOI18N
        jLabel2.setText("Exit");

        exitbutton.setIcon(new javax.swing.ImageIcon("C:\\Users\\berkb\\OneDrive\\Masaüstü\\Png and Icons\\Streamline_All_Icons_PNG\\PNG Icons\\02- Regular\\01-Interface Essential\\04-Login-Logout\\48w\\exit-1.png")); // NOI18N
        exitbutton.setText("jLabel3");
        exitbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitbuttonMouseClicked(evt);
            }
        });

        pausesongbutton.setIcon(new javax.swing.ImageIcon("C:\\Users\\berkb\\OneDrive\\Masaüstü\\Png and Icons\\Streamline_All_Icons_PNG\\PNG Icons\\02- Regular\\15-Video-Movies-TV\\06-Controls\\48w\\controls-pause.png")); // NOI18N
        pausesongbutton.setText("jLabel20");
        pausesongbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pausesongbuttonMouseClicked(evt);
            }
        });

        playsongbutton.setIcon(new javax.swing.ImageIcon("C:\\Users\\berkb\\OneDrive\\Masaüstü\\Png and Icons\\Streamline_All_Icons_PNG\\PNG Icons\\02- Regular\\15-Video-Movies-TV\\06-Controls\\48w\\controls-play.png")); // NOI18N
        playsongbutton.setText("jLabel20");
        playsongbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playsongbuttonMouseClicked(evt);
            }
        });

        playingsongname.setFont(new java.awt.Font("Ink Free", 3, 14)); // NOI18N

        playingsonsingername.setFont(new java.awt.Font("Ink Free", 3, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playingsongname, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playingsonsingername, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(186, 186, 186)
                .addComponent(pausesongbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146)
                .addComponent(playsongbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(251, 251, 251)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoutbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(exitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(playingsongname, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(logoutbutton)
                                .addComponent(exitbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(playingsonsingername, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(playsongbutton)
                            .addComponent(pausesongbutton))
                        .addGap(21, 21, 21))))
        );

        tablename.setFont(new java.awt.Font("Ink Free", 0, 24)); // NOI18N
        tablename.setText("All Songs :");

        musictable.setBackground(new java.awt.Color(255, 204, 102));
        musictable.setBorder(new javax.swing.border.MatteBorder(null));
        musictable.setFont(new java.awt.Font("Ink Free", 2, 14)); // NOI18N
        musictable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name :", "Singer : ", "Type : "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        musictable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                musictableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(musictable);
        if (musictable.getColumnModel().getColumnCount() > 0) {
            musictable.getColumnModel().getColumn(0).setResizable(false);
            musictable.getColumnModel().getColumn(1).setResizable(false);
            musictable.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        deletefromdatabase.setIcon(new javax.swing.ImageIcon("C:\\Users\\berkb\\OneDrive\\Masaüstü\\Png and Icons\\Streamline_All_Icons_PNG\\PNG Icons\\02- Regular\\01-Interface Essential\\23-Delete\\48w\\bin-2-alternate.png")); // NOI18N
        deletefromdatabase.setText("jLabel13");
        deletefromdatabase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletefromdatabaseMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Ink Free", 3, 14)); // NOI18N
        jLabel14.setText("Add new song ");

        jLabel15.setFont(new java.awt.Font("Ink Free", 3, 12)); // NOI18N
        jLabel15.setText("from database");

        jLabel16.setFont(new java.awt.Font("Ink Free", 3, 18)); // NOI18N
        jLabel16.setText("Admin Area");

        addnewsongbutton.setIcon(new javax.swing.ImageIcon("C:\\Users\\berkb\\OneDrive\\Masaüstü\\Png and Icons\\Streamline_All_Icons_PNG\\PNG Icons\\02- Regular\\01-Interface Essential\\43-Remove-Add\\48w\\add-bold.png")); // NOI18N
        addnewsongbutton.setText("jLabel17");
        addnewsongbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addnewsongbuttonMouseClicked(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Ink Free", 3, 14)); // NOI18N
        jLabel18.setText("Delete this song");

        jLabel19.setFont(new java.awt.Font("Ink Free", 3, 12)); // NOI18N
        jLabel19.setText("to database");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(101, 101, 101))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(deletefromdatabase, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addnewsongbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel19))
                .addGap(23, 23, 23))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deletefromdatabase)
                    .addComponent(addnewsongbutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel19))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        jLabel7.setFont(new java.awt.Font("Ink Free", 3, 14)); // NOI18N
        jLabel7.setText("Show my playlist");

        addsongtoplaylistbutton.setIcon(new javax.swing.ImageIcon("C:\\Users\\berkb\\OneDrive\\Masaüstü\\Png and Icons\\Streamline_All_Icons_PNG\\PNG Icons\\02- Regular\\14-Music-Audio\\16-Playlists\\48w\\playlist-add.png")); // NOI18N
        addsongtoplaylistbutton.setText("jLabel8");
        addsongtoplaylistbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addsongtoplaylistbuttonMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Ink Free", 3, 14)); // NOI18N
        jLabel9.setText("Add this song ");

        jLabel10.setFont(new java.awt.Font("Ink Free", 3, 18)); // NOI18N
        jLabel10.setText("Playlist Area  ");

        showplaylistbutton.setIcon(new javax.swing.ImageIcon("C:\\Users\\berkb\\OneDrive\\Masaüstü\\Png and Icons\\Streamline_All_Icons_PNG\\PNG Icons\\02- Regular\\14-Music-Audio\\16-Playlists\\48w\\playlist.png")); // NOI18N
        showplaylistbutton.setText("jLabel6");
        showplaylistbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showplaylistbuttonMouseClicked(evt);
            }
        });

        removesongfromplaylist.setIcon(new javax.swing.ImageIcon("C:\\Users\\berkb\\OneDrive\\Masaüstü\\Png and Icons\\Streamline_All_Icons_PNG\\PNG Icons\\02- Regular\\14-Music-Audio\\16-Playlists\\48w\\playlist-disable.png")); // NOI18N
        removesongfromplaylist.setText("jLabel11");
        removesongfromplaylist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removesongfromplaylistMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Ink Free", 3, 14)); // NOI18N
        jLabel12.setText("Remove this song");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(39, 39, 39))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(showplaylistbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addsongtoplaylistbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(removesongfromplaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel12))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showplaylistbutton)
                    .addComponent(addsongtoplaylistbutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removesongfromplaylist)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel21.setFont(new java.awt.Font("Ink Free", 3, 14)); // NOI18N
        jLabel21.setText("Song Name : ");

        searchsongname.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        searchsongname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchsongnameActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Ink Free", 3, 14)); // NOI18N
        jLabel22.setText("Singer Name : ");

        searchsingername.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        searchsingername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchsingernameActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Ink Free", 3, 14)); // NOI18N
        jLabel23.setText("Song Type : ");

        combotypebox.setFont(new java.awt.Font("Ink Free", 3, 14)); // NOI18N
        combotypebox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Every Tpye", "Rap", "Rock", "Regge", "Pop", "Electro" }));
        combotypebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combotypeboxActionPerformed(evt);
            }
        });

        serachlabelbutton.setIcon(new javax.swing.ImageIcon("C:\\Users\\berkb\\OneDrive\\Masaüstü\\Png and Icons\\Streamline_All_Icons_PNG\\PNG Icons\\02- Regular\\01-Interface Essential\\25-Search\\48w\\search-circle.png")); // NOI18N
        serachlabelbutton.setText("jLabel24");
        serachlabelbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                serachlabelbuttonMouseClicked(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Ink Free", 3, 18)); // NOI18N
        jLabel25.setText("Search Song : ");

        jLabel24.setFont(new java.awt.Font("Ink Free", 3, 14)); // NOI18N
        jLabel24.setText("Search");

        allsongshowbutton.setIcon(new javax.swing.ImageIcon("C:\\Users\\berkb\\OneDrive\\Masaüstü\\Png and Icons\\Streamline_All_Icons_PNG\\PNG Icons\\02- Regular\\14-Music-Audio\\16-Playlists\\48w\\playlist-songs.png")); // NOI18N
        allsongshowbutton.setText("jLabel5");
        allsongshowbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                allsongshowbuttonMouseClicked(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Ink Free", 3, 14)); // NOI18N
        jLabel26.setText("All Songs");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchsongname, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel24)
                                .addComponent(serachlabelbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(searchsingername, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(combotypebox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26)
                                    .addComponent(allsongshowbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(searchsongname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(searchsingername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(combotypebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serachlabelbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allsongshowbutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jLabel24))
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        playsongname.setFont(new java.awt.Font("Ink Free", 3, 14)); // NOI18N
        playsongname.setText("Selected  Song : ");

        selectedsongname.setFont(new java.awt.Font("Ink Free", 3, 18)); // NOI18N

        selectedsongsingername.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N

        selectedsongtype.setFont(new java.awt.Font("Ink Free", 1, 12)); // NOI18N

        firsttimeplaybutton.setIcon(new javax.swing.ImageIcon("C:\\Users\\berkb\\OneDrive\\Masaüstü\\Png and Icons\\Streamline_All_Icons_PNG\\PNG Icons\\02- Regular\\14-Music-Audio\\01-Music\\48w\\music-sound.png")); // NOI18N
        firsttimeplaybutton.setText("jLabel5");
        firsttimeplaybutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                firsttimeplaybuttonMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Ink Free", 3, 14)); // NOI18N
        jLabel6.setText("Play This Song");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(playsongname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectedsongsingername, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectedsongtype, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(selectedsongname, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(firsttimeplaybutton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playsongname, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectedsongname, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firsttimeplaybutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectedsongsingername, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectedsongtype, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tablename, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addComponent(tablename, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbuttonMouseClicked
        setVisible(false);
        ArrayList<user > users = new ArrayList<user>();
        loginsql sql = new loginsql();
        loginmainscreen m1 = new loginmainscreen(sql, users) ;
        m1.setVisible(true);
    }//GEN-LAST:event_logoutbuttonMouseClicked

    private void exitbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitbuttonMouseClicked
        System.exit(1);
    }//GEN-LAST:event_exitbuttonMouseClicked

    private void searchsongnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchsongnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchsongnameActionPerformed

    private void searchsingernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchsingernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchsingernameActionPerformed

    private void combotypeboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combotypeboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combotypeboxActionPerformed

    private void serachlabelbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serachlabelbuttonMouseClicked
        tablename.setText("Searhed Songs : ");       
        deletetable();
        searchmusics.removeAll(searchmusics);
        sql.searchmusic(searchsongname.getText(), searchsingername.getText(), combotypebox.getSelectedItem().toString() , searchmusics);
        
        DefaultTableModel model =  (DefaultTableModel) musictable.getModel();
        for(music music : searchmusics ){
            Object[] addiable = {music.getMusicName() , music.getArtistName() , music.getMusicType()};
            model.addRow(addiable);
        }
    }//GEN-LAST:event_serachlabelbuttonMouseClicked

    private void allsongshowbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allsongshowbuttonMouseClicked
        tablename.setText("All Songs : ");
        deletetable();
        showallmusic(sql, allmusics);
    }//GEN-LAST:event_allsongshowbuttonMouseClicked

    private void showplaylistbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showplaylistbuttonMouseClicked
        playlist.removeAll(playlist);
        sql.showplaylist(playlist, userapp);
        if(playlist.size() == 0 ){
            JOptionPane.showMessageDialog(this,"You don't have any musics in playlist.You can addd new song with song add button");
        }
        else{
            tablename.setText("Your Playlist");
            deletetable();
            DefaultTableModel model = (DefaultTableModel) musictable.getModel();
            for(music music : playlist ){
            Object[] addiable = {music.getMusicName() , music.getArtistName() , music.getMusicType()};
            model.addRow(addiable);
        }
            
        }
    }//GEN-LAST:event_showplaylistbuttonMouseClicked

    private void musictableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_musictableMouseClicked
        DefaultTableModel model = (DefaultTableModel) musictable.getModel();
        int selectedRow = musictable.getSelectedRow();
        selectedsongname.setText((String) model.getValueAt(selectedRow, 0));
        selectedsongsingername.setText((String) model.getValueAt(selectedRow, 1));
        selectedsongtype.setText((String) model.getValueAt(selectedRow, 2));
        firsttimeplaybutton.setEnabled(true);
    }//GEN-LAST:event_musictableMouseClicked

    
    public boolean isinplaylist(String musicname){
        for(music music : playlist){
            if(music.getMusicName().equals(musicname))
                return true ; 
        }
        return false ;
    }
    public music findmusic(String musicname){
        for (music music : allmusics){
            if(music.getMusicName().equals(musicname)){
                return music ; 
            }
        }
        return null ; 
    }
    
    
    
    private void addsongtoplaylistbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addsongtoplaylistbuttonMouseClicked
        if(selectedsongname.getText().length() == 0 ){
            JOptionPane.showMessageDialog(this,"!!!Firstly you shuld pick a song!!!");
        }
        else if(isinplaylist(selectedsongname.getText()) == true ){
            JOptionPane.showMessageDialog(this, "!!!Your playlist has this song!!!");
        }
        else{
            sql.addsongtoplaylist(userapp, findmusic(selectedsongname.getText()));
            JOptionPane.showMessageDialog(this, "!!!Your song has been successfully added to your playlist!!!");
            showplaylistbuttonMouseClicked(evt);
        }
            
    }//GEN-LAST:event_addsongtoplaylistbuttonMouseClicked

    private void removesongfromplaylistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removesongfromplaylistMouseClicked
        if(isinplaylist(selectedsongname.getText())== false)
            JOptionPane.showMessageDialog(this, "!!!This song is not in your playlist!!!");
        else if(selectedsongname.getText().length()== 0 )
            JOptionPane.showMessageDialog(this, "!!!Firstly you should select a song!!!");
        else{
            sql.deletemusicfromplaylist(findmusic(selectedsongname.getText()) , userapp);
            JOptionPane.showMessageDialog(this, "!!!Your song has been successfully removed from your playlist!!!");
            
            showplaylistbuttonMouseClicked(evt);
            
        }
    }//GEN-LAST:event_removesongfromplaylistMouseClicked

    private void deletefromdatabaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletefromdatabaseMouseClicked
        sql.deletesongfromdatabase(userapp, findmusic(selectedsongname.getText()));
        allsongshowbuttonMouseClicked(evt);
    }//GEN-LAST:event_deletefromdatabaseMouseClicked

    private void playsongbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playsongbuttonMouseClicked
       clip.start();
       pausesongbutton.setEnabled(true);
       playsongbutton.setEnabled(false);
       
    }//GEN-LAST:event_playsongbuttonMouseClicked

    private void pausesongbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pausesongbuttonMouseClicked
        clip.stop();
        playsongbutton.setEnabled(true);
        pausesongbutton.setEnabled(false);
        
        
    }//GEN-LAST:event_pausesongbuttonMouseClicked

    private void firsttimeplaybuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firsttimeplaybuttonMouseClicked
        try {
            clip.stop(); 
        } catch (Exception e) {
        }
       music m = findmusic(selectedsongname.getText());
       musicpath = new File(m.getMusicPath());
        try {
            System.out.println(musicpath);
            audioInput = AudioSystem.getAudioInputStream(musicpath);
            clip = AudioSystem.getClip();
            clip.open(audioInput);
            clip.start(); 
            clipTimePosition = clip.getMicrosecondPosition();
            clip.setMicrosecondPosition(clipTimePosition);
            playingsongname.setText(m.getMusicName());
            playingsonsingername.setText(m.getArtistName());
            playsongbutton.setEnabled(false);
            pausesongbutton.setEnabled(true);
            firsttimeplaybutton.setEnabled(false);
            

        } catch (Exception e) {
        }
    }//GEN-LAST:event_firsttimeplaybuttonMouseClicked

    private void addnewsongbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addnewsongbuttonMouseClicked
       addnewsong a1 = new addnewsong(sql, userapp) ; 
        setVisible(false);
        a1.setVisible(true);
    }//GEN-LAST:event_addnewsongbuttonMouseClicked

    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(appMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(appMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(appMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(appMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                user u = new user("a" , "b");
                loginsql sql  = new loginsql();
                new appMainScreen(u,sql).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addnewsongbutton;
    private javax.swing.JLabel addsongtoplaylistbutton;
    private javax.swing.JLabel allsongshowbutton;
    private javax.swing.JComboBox<String> combotypebox;
    private javax.swing.JLabel deletefromdatabase;
    private javax.swing.JLabel exitbutton;
    private javax.swing.JLabel firsttimeplaybutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel logoutbutton;
    private javax.swing.JTable musictable;
    private javax.swing.JLabel pausesongbutton;
    private javax.swing.JLabel playingsongname;
    private javax.swing.JLabel playingsonsingername;
    private javax.swing.JLabel playsongbutton;
    private javax.swing.JLabel playsongname;
    private javax.swing.JLabel removesongfromplaylist;
    private javax.swing.JTextField searchsingername;
    private javax.swing.JTextField searchsongname;
    private javax.swing.JLabel selectedsongname;
    private javax.swing.JLabel selectedsongsingername;
    private javax.swing.JLabel selectedsongtype;
    private javax.swing.JLabel serachlabelbutton;
    private javax.swing.JLabel showplaylistbutton;
    private javax.swing.JLabel tablename;
    private javax.swing.JLabel usernnamenamearea;
    // End of variables declaration//GEN-END:variables
}
